### ISSUE TITLE
Remove shipping php error

### ISSUE THREAD

**Issue by aidanjporter** [Prospress/automatewoo-subscriptions#2]
Hello!

Thank you for this plugin, so useful!

In testing, I found there was an issue with removing a shipping method.
Here is the workflow log:

```
Unexpected shutdown: PHP Fatal error Uncaught Error: Call to a member function get_method_id() on null in /wp-content/plugins/automatewoo-subscriptions-master/includes/actions/remove-shipping.php:65
Stack trace:
#0 /wp-content/plugins/automatewoo/includes/actions/subscription-edit-item-abstract.php(79): AutomateWoo_Subscriptions\Action_Subscription_Remove_Shipping->edit_subscription(Array, Object(WC_Subscription))
#1 /wp-content/plugins/automatewoo/includes/workflow.php(354): AutomateWoo\Action_Subscription_Edit_Item_Abstract->run()
#2 /wp-content/plugins/automatewoo/includes/workflow.php(219): AutomateWoo\Workflow->run()
#3 /wp-content/plugins/automatewoo/includes/abstracts/trigger.php(257): AutomateWoo\Workflow->maybe_run(Array)
#4 /wp-content/plugins/automatewoo/includes/triggers/abstract-subscriptions.php(60): AutomateWoo\Trigger->maybe_run(Array) in /wp-content/plugins/automatewoo-subscriptions-master/includes/actions/remove-shipping.php on line 65
```

Please let me know if I can provide any more detail!

**Comment by thenbrent** [comment]
Thanks for the report and stack trace @aidanjporter. This should be fixed now with SHA: eaeb814. Please update to the latest version and let me know if you encounter any other troubles.
